name: "Add Pull Request Reviewer"
description: "Adds reviewer(s) to a pull request"
branding:
  icon: "bar-chart"
  color: "green"
inputs:
  reviewers:
    description: "Reviewer(s) to add, in comma separated list."
  team_reviewers:
    description: "Team reviewer(s) to add, in comma separated list."
  token:
    description: GitHub Personal Access Token
  remove:
    description: "Remove a review request (defaults to false)"
runs:
  using: "node12"
  main: "dist/index.js"
